const galleryData = [
  { src: "/images/Galllery/3D/3croco.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/zbrush_croco.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/vadrilo.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/render3.mp4", filter: "3D", },
  { src: "/images/Galllery/3D/mesa_cosas.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/bar_render.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/render1.mp4", filter: "3D", },
  { src: "/images/Galllery/3D/lampara_techo.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/lampara_rueda_1080.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/lampara_render.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/silla.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/sombrero_1080.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/render2.mp4", filter: "3D", },
  { src: "/images/Galllery/3D/vela.jpg", filter: "3D", },
  { src: "/images/Galllery/3D/pistola.jpg", filter: "3D", },
  { src: "/images/Galllery/WEB/whale1.png", filter: "WEB" },
  { src: "/images/Galllery/WEB/whale2.png", filter: "WEB" },
  { src: "/images/Galllery/2D/base_odilia.png", filter: "2D" },
  { src: "/images/Galllery/2D/Ruda1.jpg", filter: "2D" },
  { src: "/images/Galllery/2D/cyberpunk_2.png", filter: "2D" },
  { src: "/images/Galllery/2D/star_wars.png", filter: "2D" },
  { src: "/images/Galllery/2D/desert.png", filter: "2D" },
  { src: "/images/Galllery/2D/idle_big.gif", filter: "2D" },
  { src: "/images/Galllery/2D/sapo_sake.jpg", filter: "2D" },
  { src: "/images/Galllery/2D/ladron_ninja.jpg", filter: "2D" },
  { src: "/images/Galllery/2D/dojo.jpg", filter: "2D" },
  { src: "/images/Galllery/2D/garza.jpg", filter: "2D" },
];

export default galleryData;
